name: Test Microsservices

on:
  push:
    branches: [ aula-01 ]
  pull_request:
    branches: [ aula-01 ]

jobs:
  test-auth-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        working-directory: ./burguer-app/auth-service
        run: |
          pip install -r requirements.txt
      
      - name: Run tests
        working-directory: ./burguer-app/auth-service
        run: |
          pytest -v --cov=models --cov=services --cov=config --cov=controllers
          radon cc ./models/auth_model.py

  test-product-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        working-directory: ./burguer-app/product-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        working-directory: ./burguer-app/product-service
        run: |
          pytest -v --cov=models --cov=services --cov=config --cov=controllers
          radon cc ./models/product_model.py


    test-order-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      
      - name: Install dependencies
        working-directory: ./burguer-app/order-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./burguer-app/order-service
        run: |
          pytest -v --cov=models --cov=services --cov=config --cov=controllers
          radon cc ./models/order_model.py
      
    